### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by pravi** [jonschlinkert/repeat-element#4]
We take github tarballs for debian package and it would be much easier to use tags to download releases.

**Comment by jonschlinkert** [comment]
is this tag not working? https://github.com/jonschlinkert/repeat-element/releases/tag/1.1.2 (I mean that sincerely, for some reason it didn't show the first time I clicked on it, then when I pulled down the project and was about to cut a release, I saw that it had one)

**Comment by pravi** [comment]
@jonschlinkert thanks. It was not there when I checked.
